# Generated by Django 3.0.3 on 2020-02-17 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(default=None, max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tasks',
            name='imageName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Images'),
        ),
    ]
