# Generated by Django 3.0.3 on 2020-03-11 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200217_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='imageName',
        ),
        migrations.CreateModel(
            name='Partitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partitionNumber', models.CharField(default=None, max_length=20)),
                ('cloningId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Tasks')),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Images')),
                ('taskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Tasks')),
            ],
        ),
        migrations.CreateModel(
            name='Cloning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partitionName', models.CharField(default=None, max_length=20)),
                ('taskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Tasks')),
            ],
        ),
    ]
