# Generated by Django 3.0.3 on 2020-03-12 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200311_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitions',
            name='cloningId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Cloning'),
        ),
    ]
